name: CI Test App

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  app-ci:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        node-version:
          - 14.x
    steps:
      - uses: actions/checkout@v2
      - name: Test with Node {{ matrix.node-version }}
        uses: actions/node-version@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependecies
        run: npm ci
        run: npm start &
      - name: Test
        run: npm test
          
    